name: Dependabot auto-merge

on:
  workflow_run:
    workflows: ["Pull-request"]
    types:
      - completed

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: asottile/workflows/.github/actions/fast-checkout@v1.4.1

      - name: Merge pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
        run: |
          gh pr merge $PR_NUMBER --squash --delete-branch
